### ISSUE TITLE
Null in FixedBody.getFixedList()

### ISSUE THREAD

**Issue by Xezard** [caoli5288/scoreboard#1]
Hello, caoli5288!
I copy src of your plugin "scoreboard" and try to run their with code in example, in readme.
After starting the server and log on to it, i found the NullPointerException in the console of my server.
The exception indicates that the method List<Line> list == null.
After some manipulation, i found out that returns null - build() method of the attached class Impl, in LineListBuilder class. You can fix this, please?

**Comment by caoli5288** [comment]
Paste full stacktrace and your code plz.

**Comment by caoli5288** [comment]
Ohh I got it. Fix soon.
